server/config/routes.rb
Rails.application.routes.draw do
	resources :answers

	resources :questions

	post "/users" => "users#create"
	resources :users


	get "/" => "home#home"
	get "/log-in" => "session#new"
	post "/log-in" => "session#create"
	post "/log-out" => "session#destroy", as: :log_out

	get "/getuid" => "session#uid"
end

server/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
end

server/app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers
end

server/app/models/user.rb
class User < ActiveRecord::Base
	# Set uniqueness of the user
	validates_uniqueness_of :email

	# We need a password hash
	has_secure_password

	# Questions
	has_many :questions

	#Answers
	has_many :answers

end

server/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def index
	end

	def show
	end

	def new
	end

	def edit
	end

	def create
		# Post /answers
		# params: user_id - user id
		# params: quesiton_id - question id
		# params: answer - integer value for answer

		@user = User.find(answer_params[:user_id])
		@q = Question.find(answer_params[:question_id])

		# make the associations and answer
		@answer = @user.answers.create()
		@q.answers << @answer

		#copy the answer
		@answer.update_attribute(:answer, answer_params[:answer])

		return render json: {"message" => "error"}
	end

	def update
	end

	def destroy
	end

	private
	# Never trust parameters from the scary internet, only allow the white list through.
	def answer_params
		params.require(:answer).permit(:answer, :user_id, :question_id)
	end
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	#protect_from_forgery with: :exception
	protect_from_forgery with: :null_session

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end	

	helper_method :current_user
end

server/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

server/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	skip_before_action :verify_authenticity_token

	def index
	end

	def show
		# Get /questions
		# params: id - user id
		cur_user = User.find(params[:id])
		
		unless cur_user != nil
			return redner json: {"message" => "error"}
		end

		n_qu = cur_user.questions
		#@q = Question.limit(1).where("id not in (?)", n_qu.map(&:id))
		@q = Question.first
	end

	def new
	end

	def edit
	end

	def create
		# Post /questions
		# params: user_id - user id

		@user = User.find_by(email: question_params[:email])
		#params = {"answers" => question_params[:answers], "geo" => question_params[:geo], "question" => question_params[:question], "user_id" => @user.id}
		@q = @user.questions.create()

		# Give questions value
		@q.update_attribute(:question, question_params[:question])
		@q.update_attribute(:geo, question_params[:geo])

		#@q.update_attribute(:answers, question_params[:answers].to_a)
		#@q.update_attribute(:answers, question_params[:answers])
		@q.answers = Array.new(4,"")
		@q.update_attribute(answers[0], question_params[:answer0])
		@q.update_attribute(answers[1], question_params[:answer1])
		@q.update_attribute(answers[2], question_params[:answer2])
		@q.update_attribute(answers[3], question_params[:answer3])
		@q.save


		# Answer stuff
		@answer = @q.answers.create()
		@user.answers << @answer

		# Copy the answer
		@answer.update_attribute(:answer, nil)

		return render json: {"message" => "success"}

	end

	def update
	end

	def destroy
	end

	def getQuestion
		# get /getquestion
		# params: user_id - user id
		@user = User.find_by(email: question_params[:email])

		# Select Question.question, Question.id, Question.answers from Questions 
		# inner join Answers 
		# on Questions.user_id=Answers.user_id 
		# where Questions.user_id <> @user.id
		Question.answers
		Q - A_U

	end

	private
	def question_params
      params.require(:question).permit(:question, :geo, :email, :answer0, :answer1, :answer2, :answer3)
    end
end

server/app/controllers/session_controller.rb
class SessionController < ApplicationController
	protect_from_forgery :except => :create

	def new
	end

	def create 
		@user = User.find_by(email: params[:email])
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			return render json: {:message => "success"}
		else 
			return render json: {:message => "fail"}
		end
	end

	def destroy
		session[:user_id] = nil
	end

	def uid 
		@user = User.find_by(email: params[:email])
		return render json: {"id" => @user.id}
	end

end

server/app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :verify_authenticity_token

	def new
	end

	def edit
	end

	def create
		@user = User.new(user_params)

		if @user.save
			#session[:user_id] = @user.id
			return render json: {"message" => "success"}
		else
			return render json: {"message" => "error"}
		end
	end

	def update
	end

	def destroy
	end

	private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation) if params[:user]
	end
end

server/app/helpers/answers_helper.rb
module AnswersHelper
end

server/app/helpers/home_helper.rb
module HomeHelper
end

server/app/helpers/questions_helper.rb
module QuestionsHelper
end

server/app/helpers/session_helper.rb
module SessionHelper
end

server/app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

server/app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.user_id %></td>
        <td><%= answer.question_id %></td>
        <td><%= answer.answer %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

server/app/views/answers/new.html.erb
<h1>New Answers</h1>

<%=form_for Answer.new do |f| %>
	<%=f.label :user_id %>
	<%=f.number_field :user_id %> 
	<%=f.label :question_id %>
	<%=f.number_field :question_id %> 
	<%=f.label :answer %>
	<%=f.text_field :answer%> 
	<%=f.submit "Create Answer" %>
<%end%>

server/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

server/app/views/home/home.html.erb
<h1>Home#home</h1>
<p>Find me in app/views/home/home.html.erb</p>
<%if current_user != nil %>
	<%= current_user.email %> <br>
<%else %>
	banana
<%end %>

server/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :options %><br>
    <%= f.text_area :options %>
  </div>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :geo %><br>
    <%= f.text_area :geo %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

server/app/views/questions/index.html.erb
<h1>Listing questions</h1>

server/app/views/questions/new.html.erb
<h1>New question</h1>

<h1>Generate Question</h1>

<%=form_for Question.new do |f| %>
	<%=f.label :question %>
	<%=f.text_field :question %> 
	<%=f.label :geo %>
	<%=f.text_field :geo %>
	<%=f.label :user_id %>
	<%=f.text_field :user_id %>
	<%=f.submit "Create Question" %>
<%end%>

server/app/views/questions/show.html.erb
<h2> Banana </h2>
<%= @q.question %>

server/app/views/session/new.html.erb
<h1>Log In</h1>

<%=form_tag log_in_path do%>
	<%=label_tag :email %>
	<%=text_field_tag :email %>
	<%=label_tag :password %>
	<%=password_field_tag :password %>
	<%=submit_tag "Log in" %>
<%end%>

server/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%=form_for User.new do |f| %>
	<%=f.label :email %>
	<%=f.text_field :email %> 
	<%=f.label :password %>
	<%=f.password_field :password %> 
	<%=f.label :password_confirmation %>
	<%=f.password_field :password_confirmation %>
	<%=f.submit "Sign Up" %>
<%end%>